import React from 'react';
import {
  Phone,
  PhoneCall,
  Mail,
  MapPin,
  MessageCircle,
  Search,
  ShieldCheck,
  LockKeyhole,
  Lock,
  UserSearch,
  UserCheck,
  User,
  Building2,
  Building,
  FileSearch,
  FolderSearch,
  Camera,
  BriefcaseBusiness,
  Briefcase,
  HeartHandshake,
  Users,
  ClipboardCheck,
  FileCheck,
  FileCheck2,
  Clock,
  ArrowRight,
  ArrowUpRight,
  ArrowLeft,
  CheckCircle,
  CheckCircle2,
  AlertCircle,
  ShieldAlert,
  AlertTriangle,
  Menu,
  X,
  XCircle,
  Scale,
  Fingerprint,
  Shield,
  Cpu,
  Compass,
  FileText,
  Activity,
  Key,
  KeyRound,
  Globe,
  Globe2,
  Database,
  Eye,
  EyeOff,
  Sparkles,
  Award,
  HelpCircle,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Filter,
  RefreshCw,
  Plus,
  Trash2,
  Edit2,
  Edit3,
  ExternalLink,
  Save,
  Check,
  Star,
  Quote,
  MessageSquareQuote,
  MessageSquare,
  HardDrive,
  Info,
  Calendar,
  Send,
  Inbox,
  FolderKanban,
  LayoutDashboard,
  Settings,
  Bell,
  LogOut,
  LucideIcon
} from 'lucide-react';

/**
 * Centralized Icon Mapping for Services, Categories, and Action Icons
 * Ensures consistent Lucide React iconography across the SeekProof application.
 */
export const SERVICE_ICON_MAP: Record<string, LucideIcon> = {
  // Service slugs & identifiers
  'corporate-fraud': Building2,
  'corporate-fraud-investigation': Building2,
  'corporate-investigation': Building2,
  'digital-forensics': Cpu,
  'digital-forensics-investigation': Cpu,
  'asset-recovery': Compass,
  'asset-tracing': Compass,
  'asset-tracing-recovery': Compass,
  'counter-surveillance': Eye,
  'tscm-counter-surveillance-sweeps': Eye,
  'due-diligence': Fingerprint,
  'strategic-due-diligence': Fingerprint,
  'field-surveillance': Camera,
  'surveillance': Camera,
  'marital-investigations': HeartHandshake,
  'pre-matrimonial': HeartHandshake,
  'post-matrimonial-investigations': ShieldAlert,
  'infidelity-investigation': ShieldAlert,
  'missing-persons': UserSearch,
  'missing-person-tracing': UserSearch,
  'personal-investigation': UserCheck,
  'lady-detectives': UserSearch,
  'background-checks-verifications': ClipboardCheck,
  'background-checks': ClipboardCheck,
  'identity-verification': ShieldCheck,
  'forensic-analysis-legal-support': Scale,
  'corporate-security': Shield,
  'risk-mitigation': ShieldCheck,

  // Direct icon name lookups (case-insensitive keys handled in helper)
  phone: Phone,
  phonecall: PhoneCall,
  mail: Mail,
  mappin: MapPin,
  messagecircle: MessageCircle,
  search: Search,
  shieldcheck: ShieldCheck,
  lockkeyhole: LockKeyhole,
  lock: LockKeyhole,
  usersearch: UserSearch,
  usercheck: UserCheck,
  user: User,
  building2: Building2,
  building: Building2,
  filesearch: FileSearch,
  foldersearch: FolderSearch,
  camera: Camera,
  briefcasebusiness: BriefcaseBusiness,
  briefcase: BriefcaseBusiness,
  hearthandshake: HeartHandshake,
  users: Users,
  clipboardcheck: ClipboardCheck,
  filecheck: ClipboardCheck,
  filecheck2: ClipboardCheck,
  clock: Clock,
  arrowright: ArrowRight,
  checkcircle: CheckCircle2,
  checkcircle2: CheckCircle2,
  alertcircle: AlertCircle,
  shieldalert: ShieldAlert,
  menu: Menu,
  x: X,
  scale: Scale,
  fingerprint: Fingerprint,
  shield: Shield,
  cpu: Cpu,
  compass: Compass,
  filetext: FileText,
  activity: Activity,
  key: KeyRound,
  globe: Globe2,
  database: Database,
  eye: Eye,
  eyeoff: EyeOff,
  sparkles: Sparkles,
  award: Award,
  helpcircle: HelpCircle
};

/**
 * Category-level default icon mapping
 */
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  'Corporate': Building2,
  'Corporate Intelligence': Building2,
  'Cyber & OSINT': Cpu,
  'Financial Intelligence': Compass,
  'Physical & Electronic Defense': Eye,
  'Risk Mitigation': ShieldCheck,
  'Field Operations': Camera,
  'Personal': UserCheck,
  'Personal Matters': UserCheck,
  'Matrimonial': HeartHandshake,
  'Matrimonial & Family': HeartHandshake,
  'Verification': ClipboardCheck,
  'Security': Shield,
  'Legal Support': Scale,
  'Location & Tracing': UserSearch
};

/**
 * Retrieves the appropriate LucideIcon for a service slug, icon name, or category.
 */
export function getServiceIcon(
  identifier?: string | null,
  fallback: LucideIcon = Shield
): LucideIcon {
  if (!identifier) return fallback;

  const normalized = identifier.toLowerCase().trim().replace(/[\s_-]+/g, '-');
  const directMatch = SERVICE_ICON_MAP[normalized];
  if (directMatch) return directMatch;

  const strippedKey = identifier.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (SERVICE_ICON_MAP[strippedKey]) {
    return SERVICE_ICON_MAP[strippedKey];
  }

  if (CATEGORY_ICON_MAP[identifier]) {
    return CATEGORY_ICON_MAP[identifier];
  }

  // Case-insensitive check on category map
  const catKey = Object.keys(CATEGORY_ICON_MAP).find(
    k => k.toLowerCase() === identifier.toLowerCase().trim()
  );
  if (catKey) return CATEGORY_ICON_MAP[catKey];

  return fallback;
}

// Re-export common icon components for unified consumption
export {
  Phone,
  PhoneCall,
  Mail,
  MapPin,
  MessageCircle,
  Search,
  ShieldCheck,
  LockKeyhole,
  Lock,
  UserSearch,
  UserCheck,
  User,
  Building2,
  Building,
  FileSearch,
  FolderSearch,
  Camera,
  BriefcaseBusiness,
  Briefcase,
  HeartHandshake,
  Users,
  ClipboardCheck,
  FileCheck,
  FileCheck2,
  Clock,
  ArrowRight,
  ArrowUpRight,
  ArrowLeft,
  CheckCircle,
  CheckCircle2,
  AlertCircle,
  ShieldAlert,
  AlertTriangle,
  Menu,
  X,
  XCircle,
  Scale,
  Fingerprint,
  Shield,
  Cpu,
  Compass,
  FileText,
  Activity,
  Key,
  KeyRound,
  Globe,
  Globe2,
  Database,
  Eye,
  EyeOff,
  Sparkles,
  Award,
  HelpCircle,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Filter,
  RefreshCw,
  Plus,
  Trash2,
  Edit2,
  Edit3,
  ExternalLink,
  Save,
  Check,
  Star,
  Quote,
  MessageSquareQuote,
  MessageSquare,
  HardDrive,
  Info,
  Calendar,
  Send,
  Inbox,
  FolderKanban,
  LayoutDashboard,
  Settings,
  Bell,
  LogOut
};
